language: node_js
node_js:
    - "8"
sudo: false
branches:
    only:
    - master

 # Run npm test always
script:
    - "npm test"
    - ./changefile.sh
before_deploy:
    - ./deploy.sh
deploy:
    provider: npm
    email: $NPM_EMAIL
    api_key: $NPM_KEY
    on:
        tags: true
        all_branches: true
