language: node_js
node_js:
    - "8"

env:
    global:
        - GIT_NAME: Travis CI
        - GIT_EMAIL: builds@travis-ci.org
        - GIT_BRANCH: master
sudo: false

 # Run npm test always
script:
    - "npm test"
    - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
    - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"
    - echo "Tag=$TRAVIS_TAG"
    - node build.js
