language: node_js
node_js:
    - "8"

env:
    global:
        - GIT_NAME: Travis CI
        - GIT_EMAIL: builds@travis-ci.org
        - TRAVIS_REPO_SLUG: viatorus/TestProject
        - GIT_BRANCH: master
sudo: false
branches:
    only:
    - master

 # Run npm test always
script:
    - "npm test"
    - git config credential.helper "store --file=.git/credentials"
    - echo "https://${GH_TOKEN}:@github.com" > .git/credentials
    - ./changefile.sh
    - ./deploy.sh
deploy:
    provider: npm
    email: $NPM_EMAIL
    api_key: $NPM_KEY
    on:
        tags: true
        all_branches: true
