language: node_js
node_js:
    - "8"

env:
    global:
        - GIT_NAME: Travis CI
        - GIT_EMAIL: builds@travis-ci.org
        - TRAVIS_REPO_SLUG: viatorus/TestProject
        - GIT_BRANCH: master
sudo: false

 # Run npm test always
script:
    - "npm test"
    - node build.js
