language: node_js
node_js:
    - "8"

env:
    global:
        - GIT_NAME: Travis CI
        - GIT_EMAIL: builds@travis-ci.org
        - GIT_BRANCH: master
sudo: false

 # Run npm test always
script:
    - "npm test"
    - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then echo "direct push to master"; fi
    - test $TRAVIS_PULL_REQUEST = false && echo "not a pull request"
    - if [ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ "${TRAVIS_BRANCH}" = "master" ]; then echo "anything"; fi
    - echo "1111111111111111111111111111111111111111111111111111111111"
    - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
    - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"
    - echo "Tag=$TRAVIS_TAG"
    - node build.j
